# Generated by Django 4.1.5 on 2023-06-25 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts2', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YourModel',
        ),
    ]
