# Generated by Django 4.2.1 on 2023-06-26 04:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts2", "0005_alter_customer_options_alter_customer_managers_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={},
        ),
        migrations.AlterModelManagers(
            name="customer",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="customer",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="user_permissions",
        ),
        migrations.AlterField(
            model_name="customer",
            name="last_login",
            field=models.DateTimeField(
                auto_now=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customer",
            name="username",
            field=models.CharField(max_length=30),
        ),
    ]
