# Generated by Django 4.2.1 on 2023-06-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts2", "0006_alter_customer_options_alter_customer_managers_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="emplyee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=20)),
                ("paswword", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=20)),
                ("role", models.CharField(max_length=20)),
            ],
            options={
                "ordering": ["role"],
            },
        ),
        migrations.DeleteModel(
            name="customer",
        ),
    ]
