# Generated by Django 4.1.13 on 2024-03-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts2", "0008_event_participant_registration_delete_emplyee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="participant",
            name="role",
        ),
        migrations.RemoveField(
            model_name="participant",
            name="user",
        ),
        migrations.AddField(
            model_name="participant",
            name="email",
            field=models.EmailField(
                default="nadeem@gmail.com", max_length=254, unique=True
            ),
        ),
        migrations.AddField(
            model_name="participant",
            name="name",
            field=models.CharField(default="user", max_length=100),
        ),
    ]
